// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```gwstg

 //efqwf

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dG96RtDzq4cUdTnZY7__jgX8eDWtRdA',
    appId: '1:59322546908:android:631146cd62cdfeb7e11219',
    messagingSenderId: '59322546908',
    projectId: 'nftwist-1feb5',
    storageBucket: 'nftwist-1feb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD76IbfMrzTo0idQSTMYclQBiIB2JB0s1o',
    appId: '1:59322546908:ios:a020bb76959bf43ce11219',
    messagingSenderId: '59322546908',
    projectId: 'nftwist-1feb5',
    storageBucket: 'nftwist-1feb5.appspot.com',
    androidClientId: '59322546908-nmbe8j1uhc11nnl96821rqnoe0h2adsk.apps.googleusercontent.com',
    iosClientId: '59322546908-8p9iciubvt16ld6ga9vc7anmbc8na0g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nftwist',
  );
}
